name: Run tests

on: 
  push:
    paths:
      - '*.go'
      - 'go.*'
    branches:
      - '*'
    tags: 
      - '!*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v1
      - name: Run tests
        run: go test .
